Develop
mklim1005/Sprint_3 pull request #1
Opened 2022-04-26 13:45 UTC by mklim1005

Sprint_3

2022-04-26 14:52 UTC, alstafeev requested changes
Хорошая работа, молодец
Есть моменты которые надо поправить
Жду исправлений

2022-04-26 14:52 UTC, alstafeev commented on src/main/java/ScooterRegisterCourier.java
> +        String registerRequestBody = "{\"login\":\"" + courierLogin + "\","
Тут лучше использовать Map
Например так 

`registerRequestBody =
                Map.of("login", courierLogin,
                        "password", courierPassword,
                        "firstName", courierFirstName);`

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestLogInCourier.java
> +    public void testLogInWrongPassword(){
Нужно добавить еще тест с не верным логином

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestOrderCreation.java
> +        order = new Order("Mrr","Puh","Moscow",4,"+7839276",5,"2022-04-30","Haha");
У тебя есть конструктор с этими значениями ордера, зачем тут передавать эти же значения хардкодом?
Предлагаю убрать, чтобы не дублировать

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestListOfOrders.java
> +        response.then().assertThat().body("orders", notNullValue());
Нужно проверить что вернулся список заказов, а не просто проверка на null

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestAcceptOrder.java
> +        order = new Order("Vinni","Puh","Moscow",4,"+7839276",5,"2022-04-30","Haha");
Опять же у тебя уже есть конструктор с данными значениями, не обязательно тут передавать их еще раз

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestAcceptOrder.java
> +    public void setUp() {
Надо дописать метод @After с удалением тестовых данных, которые создавались тут для теста

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/ParametrizedOrderCreationTest.java
> +    public void shouldCreateOrder() {
После теста нужно удалять созданные данные

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestGetOrderByTrack.java
> +    @Before
Нужно удалять данные после теста

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestLogInCourier.java
> +    ArrayList<String> newCourierWithCredentials = newCourier.registerNewCourierAndReturnLoginPassword();
После теста надо удалять тестовые данные

2022-04-26 14:52 UTC, alstafeev commented on src/test/java/TestOrderCreation.java
> +    @Before
После теста надо удалять тестовые данные

2022-04-26 14:52 UTC, alstafeev commented on src/main/java/ScooterRegisterCourier.java
> +        ArrayList<String> loginPass = new ArrayList<>();
Можно возвращать не список, а объект
У тебя есть класс Courier
Почему бы не возвращать объект класса, вместо списка

2022-05-01 09:47 UTC, mklim1005 commented on src/test/java/TestLogInCourier.java
> +    public void testLogInWrongPassword(){
fixed

2022-05-01 11:12 UTC, mklim1005 commented on src/test/java/ParametrizedOrderCreationTest.java
> +    public void shouldCreateOrder() {
@alstafeev В этом тесте мы создаем заказ, в API нет метода для удаления заказа. Есть методы "Завершить заказ" и "Отменить заказ".

2022-05-01 11:24 UTC, mklim1005 commented on src/test/java/TestGetOrderByTrack.java
> +    @Before
@alstafeev В этом тесте мы создаем заказ, в API нет метода для удаления заказа. Есть методы "Завершить заказ" и "Отменить заказ".

2022-05-02 12:15 UTC, mklim1005 commented
added fixes

2022-05-03 11:02 UTC, alstafeev approved these changes

2022-05-13 06:59 UTC, merged